kind: pipeline
name: default
steps:
  - name: test
    image: ocaml/opam2:4.05
    commands:
      - sudo apt update
      - sudo apt install -y libgmp-dev perl pkg-config libssl-dev m4
      - sudo chown -R opam .
      - git -C /home/opam/opam-repository pull origin && opam update
      - opam install -y yurt lwt irmin-unix odate omd mustache yaml lwt_ssl lambdasoup dune
      - eval $(opam config env)
      - make
