kind: pipeline
name: default
steps:
  - name: test
    image: ocaml/opam2:4.05
    commands:
      - sudo apt update
      - sudo apt install -y libgmp-dev perl pkg-config libssl-dev m4
      - sudo chown -R opam .
      - git -C /home/opam/opam-repository pull origin && opam update
      - opam pin add ssl 0.5.5
      - opam install -y opium lwt_ppx stdint dolog alcotest lwt irmin-unix odate omd mustache yaml lwt_ssl lambdasoup dune
      - eval $(opam config env)
      - export CONDUIT_TLS=openssl
      # Build the entriespub binary
      - make
      # Unit tests
      - dune runtest
